In [25]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [26]:
group_name = pd.read_csv("data/cnf-fcen-csv/FOOD GROUP.csv", encoding="ISO-8859-1")
group_name

,FoodGroupID,FoodGroupCode,FoodGroupName,FoodGroupNameF
0,1,1,Dairy and Egg Products,Produits laitiers et d'oeufs\n
1,2,2,Spices and Herbs,Épices et fines herbes
2,3,3,Babyfoods,Aliments pour bébés
3,4,4,Fats and Oils,Matières grasses et huiles
4,5,5,Poultry Products,Produits de volaille
5,6,6,"Soups, Sauces and Gravies",Potages et sauces
6,7,7,Sausages and Luncheon meats,Saucisses et viandes froides
7,8,8,Breakfast cereals,Céréales à déjeuner
8,9,9,Fruits and fruit juices,Fruits et jus de fruits
9,10,10,Pork Products,Produits de porc
10,11,11,Vegetables and Vegetable Products,Légumes et produits végétaux
11,12,12,Nuts and Seeds,Noix et graines
12,13,13,Beef Products,Produits de boeuf
13,14,14,Beverages,Boissons
14,15,15,Finfish and Shellfish Products,"Produits de poissons, mollusques et crustacés"
15,16,16,Legumes and Legume Products,Légumineuses et produits de légumineuses
16,17,17,"Lamb, Veal and Game","Ageau, veau et gibier"
17,18,18,Baked Products,Produits de boulangerie
18,19,19,Sweets,Sucreries
19,20,20,"Cereals, Grains and Pasta","Céréales, grains et pâtes"
20,21,21,Fast Foods,Aliments prêts-à-manger
21,22,22,Mixed Dishes,Mets composés
22,25,25,Snacks,Grignotises

In [28]:
footprints = pd.read_csv("data/food-footprints.csv")
footprints = footprints[["Entity", "GHG emissions per kilogram (Poore & Nemecek, 2018)"]]
footprints

               Entity  GHG emissions per kilogram (Poore & Nemecek, 2018)
0              Apples                                               0.43
1             Bananas                                               0.86
2              Barley                                               1.18
3    Beef (beef herd)                                              99.48
4   Beef (dairy herd)                                              33.30
5          Beet Sugar                                               1.81
6    Berries & Grapes                                               1.53
7           Brassicas                                               0.51
8          Cane Sugar                                               3.20
9             Cassava                                               1.32
10             Cheese                                              23.88
11       Citrus Fruit                                               0.39
12             Coffee                                              28.53
13     Dark Chocolate                                              46.65
14               Eggs                                               4.67
15      Fish (farmed)                                              13.63
16         Groundnuts                                               3.23
17      Lamb & Mutton                                              39.72
18              Maize                                               1.70
19               Milk                                               3.15
20               Nuts                                               0.43
21            Oatmeal                                               2.48
22     Onions & Leeks                                               0.50
23        Other Fruit                                               1.05
24       Other Pulses                                               1.79
25   Other Vegetables                                               0.53
26               Peas                                               0.98
27           Pig Meat                                              12.31
28           Potatoes                                               0.46
29       Poultry Meat                                               9.87
30    Prawns (farmed)                                              26.87
31               Rice                                               4.45
32    Root Vegetables                                               0.43
33           Soy milk                                               0.98
34               Tofu                                               3.16
35           Tomatoes                                               2.09
36        Wheat & Rye                                               1.57
37               Wine                                               1.79

In [29]:
footprints.loc[len(footprints)] = ["Dairy Products", (3.15 + 4.67 + 0.98) / 3]
footprints.loc[len(footprints)] = ["Species", 9.3703]
footprints.loc[len(footprints)] = ["Oils", (3.0336 + 4.2483 + 3.0231 + 3.2401 + 5.6383) / 5]
footprints.loc[len(footprints)] = ["Sauces", 0]
footprints.loc[len(footprints)] = ["Cereals", 1.4785]
footprints.loc[len(footprints)] = ["Fruits", (0.43 + 0.86 + 0.39 + 1.05) / 4]
footprints.loc[len(footprints)] = ["Beef", (99.48 + 33.3) / 2]
footprints.loc[len(footprints)] = ["Fruits", (0.43 + 0.86 + 0.39 + 1.05) / 4]
footprints.loc[len(footprints)] = ["Beverages", 0]
footprints.loc[len(footprints)] = ["Legumes", 1.6042]
footprints.loc[len(footprints)] = ["Sweets", (1.5225 + 1.6414) / 2]
footprints = footprints.rename(columns={"GHG emissions per kilogram (Poore & Nemecek, 2018)" : "GHG emissions per kilogram"})
footprints

               Entity  GHG emissions per kilogram
0              Apples                    0.430000
1             Bananas                    0.860000
2              Barley                    1.180000
3    Beef (beef herd)                   99.480000
4   Beef (dairy herd)                   33.300000
5          Beet Sugar                    1.810000
6    Berries & Grapes                    1.530000
7           Brassicas                    0.510000
8          Cane Sugar                    3.200000
9             Cassava                    1.320000
10             Cheese                   23.880000
11       Citrus Fruit                    0.390000
12             Coffee                   28.530000
13     Dark Chocolate                   46.650000
14               Eggs                    4.670000
15      Fish (farmed)                   13.630000
16         Groundnuts                    3.230000
17      Lamb & Mutton                   39.720000
18              Maize                    1.700000
19               Milk                    3.150000
20               Nuts                    0.430000
21            Oatmeal                    2.480000
22     Onions & Leeks                    0.500000
23        Other Fruit                    1.050000
24       Other Pulses                    1.790000
25   Other Vegetables                    0.530000
26               Peas                    0.980000
27           Pig Meat                   12.310000
28           Potatoes                    0.460000
29       Poultry Meat                    9.870000
30    Prawns (farmed)                   26.870000
31               Rice                    4.450000
32    Root Vegetables                    0.430000
33           Soy milk                    0.980000
34               Tofu                    3.160000
35           Tomatoes                    2.090000
36        Wheat & Rye                    1.570000
37               Wine                    1.790000
38     Dairy Products                    2.933333
39            Species                    9.370300
40               Oils                    3.836680
41             Sauces                    0.000000
42            Cereals                    1.478500
43             Fruits                    0.682500
44               Beef                   66.390000
45             Fruits                    0.682500
46          Beverages                    0.000000
47            Legumes                    1.604200
48             Sweets                    1.581950

In [31]:
footprints.to_csv("cleaned_data/carbon_footprints.csv", index=False)

In [33]:
map_category = {"Dairy and Egg Products" : "Dairy Products",
                "Spices and Herbs" : "Species",
                "Fats and Oils" : "Oils",
                "Poultry Products" : "Poultry Meat",
                "Soups, Sauces and Gravies" : "Sauces",
                "Sausages and Luncheon meats" : "Pig Meat",
                "Breakfast cereals" : "Cereals",
                "Fruits and fruit juices" : "Fruits",
                "Pork Products" : "Pig Meat",
                "Vegetables and Vegetable Products" : "Other Vegetables",
                "Nuts and Seeds" : "Nuts",
                "Beef Products" : "Beef",
                "Finfish and Shellfish Products" : "Fish (farmed)",
                "Legumes and Legume Products" : "Legumes",
                "Lamb, Veal and Game" : "Lamb & Mutton",
                "Baked Products" : "Wheat & Rye",
                "Sweets" : "Sweets",
                "Beverages" : "Beverages",
                "Cereals, Grains and Pasta" : "Cereals"}

In [34]:
def category_mapper(category, emission_df, map_category):
    mapped_category = map_category[category]
    emission_factor = emission_df.loc[emission_df["Entity"] == mapped_category]["GHG emissions per kilogram"].values[0]
    return emission_factor

In [35]:
nutrition = pd.read_csv("data/cnf-fcen-csv/NUTRIENT AMOUNT.csv", encoding="ISO-8859-1")
nutrition

,FoodID,NutrientID,NutrientValue,StandardError,NumberofObservations,NutrientSourceID,NutrientDateOfEntry
0,2,203,9.54,0.0,0.0,102,2010-04-16
1,2,204,15.70,0.0,0.0,102,2010-04-16
2,2,205,5.91,0.0,0.0,102,2010-04-16
3,2,207,1.67,0.0,0.0,102,2010-04-16
4,2,208,204.00,0.0,0.0,102,2010-04-16
...,...,...,...,...,...,...,...
524669,503380,861,0.00,NaN,NaN,0,2015-05-29
524670,503380,862,12.40,NaN,NaN,0,2015-05-29
524671,503380,863,3.30,NaN,NaN,0,2015-05-29
524672,503380,874,0.00,NaN,NaN,0,2015-05-29
524673,503380,875,0.00,NaN,NaN,0,2015-05-29

In [36]:
food_name = pd.read_csv("data/cnf-fcen-csv/FOOD NAME.csv", encoding="ISO-8859-1")
food_name

,FoodID,FoodCode,FoodGroupID,FoodSourceID,FoodDescription,FoodDescriptionF,FoodDateOfEntry,FoodDateOfPublication,CountryCode,ScientificName
0,2,2,22,20,Cheese souffle,Soufflé au fromage,1981-01-01,NaN,NaN,NaN
1,4,4,22,20,"Chop suey, with meat, canned","Chop suey, avec viande, conserve",1981-01-01,NaN,NaN,NaN
2,5,5,22,0,"Chinese dish, chow mein, chicken","Mets chinois, chow mein, poulet",1981-01-01,NaN,36623.0,NaN
3,6,6,18,20,Corn fritter,"Maïs, beignet",1981-01-01,NaN,NaN,NaN
4,7,7,22,36,"Beef pot roast, with browned potatoes, peas an...","Boeuf braisé, avec pomme de terre au four, poi...",1981-01-01,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
5685,503365,7573,9,26,"Orange juice, frozen concentrate, diluted, wit...","Jus d'orange, concentré, dilué, calcium et vit...",2015-02-25,NaN,NaN,NaN
5686,503366,7574,4,38,"Margarine, tub, hydrogenated, soybean oil","Margarine, molle, hydrogénée, huile de soya",2015-03-02,NaN,NaN,NaN
5687,503367,7575,4,38,"Margarine, tub, hydrogenated, canola oil","Margarine, molle, hydrogénée, huile de canola",2015-03-02,NaN,NaN,NaN
5688,503379,7577,14,26,"Chocolate syrup, thin type, less sugar, with a...","Chocolat, sirop, consistance claire, moins de ...",2015-05-26,NaN,19916.0,NaN
5689,503380,7578,18,1,"Granola bar, chewy, high fibre, oats and choco...","Barre granola, tendre, élevée en fibres, avoin...",2015-05-29,NaN,25045.0,NaN

In [37]:
nutrition_name = pd.read_csv("data/cnf-fcen-csv/NUTRIENT NAME.csv", encoding="ISO-8859-1")
nutrition_name

,NutrientID,NutrientCode,NutrientSymbol,NutrientUnit,NutrientName,NutrientNameF,Tagname,NutrientDecimals
0,203,203,PROT,g,PROTEIN,PROTÉINES,PROCNT,2
1,204,204,FAT,g,FAT (TOTAL LIPIDS),LIPIDES TOTAUX,FAT,2
2,205,205,CARB,g,"CARBOHYDRATE, TOTAL (BY DIFFERENCE)",GLUCIDES TOTAUX (PAR DIFFÉRENCE),CHOCDF,2
3,207,207,ASH,g,"ASH, TOTAL","CENDRES, TOTALES",ASH,2
4,208,208,KCAL,kCal,ENERGY (KILOCALORIES),ÉNERGIE (KILOCALORIES),ENERC_KCAL,0
...,...,...,...,...,...,...,...,...
147,847,860,12:1,g,"FATTY ACIDS, MONOUNSATURATED, 12:1, LAUROLEIC","ACIDES GRAS MONOINSATURÉS, 12:1, LAUROLEIC",F12D1,3
148,848,861,22:3,g,"FATTY ACIDS, POLYUNSATURATED, 22:3,","ACIDES GRAS POLYINSATURÉS, 22:3",F22D3,3
149,849,862,22:2,g,"FATTY ACIDS, POLYUNSATURATED, 22:2, DOCOSADIENOIC","ACIDES GRAS POLYINSATURÉS, 22:2, DOCOSADIÉNOÏQUE",F22D2,3
150,868,902,TOmega n-3,g,"FATTY ACIDS, POLYUNSATURATED, TOTAL OMEGA N-3","ACIDES GRAS POLYINSATURÉS, TOTAUX D'OMÉGA N-3\n",FAPUN3,3
151,869,903,TOmega n-6,g,"FATTY ACIDS, POLYUNSATURATED, TOTAL OMEGA N-6","ACIDES GRAS POLYINSATURÉS, TOTAUX D'OMÉGA N-6",FAPUN6,3

In [38]:
df_merged = food_name[["FoodID", "FoodDescription", "FoodGroupID"]].merge(nutrition[["FoodID", "NutrientID", "NutrientValue"]], on="FoodID")
df_merged

,FoodID,FoodDescription,FoodGroupID,NutrientID,NutrientValue
0,2,Cheese souffle,22,203,9.54
1,2,Cheese souffle,22,204,15.70
2,2,Cheese souffle,22,205,5.91
3,2,Cheese souffle,22,207,1.67
4,2,Cheese souffle,22,208,204.00
...,...,...,...,...,...
524669,503380,"Granola bar, chewy, high fibre, oats and choco...",18,861,0.00
524670,503380,"Granola bar, chewy, high fibre, oats and choco...",18,862,12.40
524671,503380,"Granola bar, chewy, high fibre, oats and choco...",18,863,3.30
524672,503380,"Granola bar, chewy, high fibre, oats and choco...",18,874,0.00
524673,503380,"Granola bar, chewy, high fibre, oats and choco...",18,875,0.00

In [39]:
df_merged = df_merged.merge(group_name[["FoodGroupID", "FoodGroupName"]], on="FoodGroupID")
df_merged

,FoodID,FoodDescription,FoodGroupID,NutrientID,NutrientValue,FoodGroupName
0,2,Cheese souffle,22,203,9.540,Mixed Dishes
1,2,Cheese souffle,22,204,15.700,Mixed Dishes
2,2,Cheese souffle,22,205,5.910,Mixed Dishes
3,2,Cheese souffle,22,207,1.670,Mixed Dishes
4,2,Cheese souffle,22,208,204.000,Mixed Dishes
...,...,...,...,...,...,...
524669,502713,"Fast food, biscuit",21,852,0.000,Fast Foods
524670,502713,"Fast food, biscuit",21,854,0.000,Fast Foods
524671,502713,"Fast food, biscuit",21,855,0.004,Fast Foods
524672,502713,"Fast food, biscuit",21,859,0.035,Fast Foods
524673,502713,"Fast food, biscuit",21,861,0.000,Fast Foods

In [40]:
df_merged = df_merged.merge(nutrition_name[["NutrientID", "NutrientName", "NutrientUnit"]], on="NutrientID")
df_merged

,FoodID,FoodDescription,FoodGroupID,NutrientID,NutrientValue,FoodGroupName,NutrientName,NutrientUnit
0,2,Cheese souffle,22,203,9.54,Mixed Dishes,PROTEIN,g
1,4,"Chop suey, with meat, canned",22,203,4.07,Mixed Dishes,PROTEIN,g
2,5,"Chinese dish, chow mein, chicken",22,203,6.76,Mixed Dishes,PROTEIN,g
3,7,"Beef pot roast, with browned potatoes, peas an...",22,203,21.29,Mixed Dishes,PROTEIN,g
4,8,"Fried chicken, mashed potatoes and vegetables",22,203,12.80,Mixed Dishes,PROTEIN,g
...,...,...,...,...,...,...,...,...
524668,2505,"Potato, flesh and skin, raw",11,245,0.05,Vegetables and Vegetable Products,OXALIC ACID,mg
524669,5982,"Beef, chuck, cross rib roast, boneless, lean a...",13,245,0.00,Beef Products,OXALIC ACID,mg
524670,6002,"Beef, hip, eye of round steak, boneless, lean,...",13,245,0.00,Beef Products,OXALIC ACID,mg
524671,6132,"Beef, loin, tenderloin, steak, lean and fat, 0...",13,245,0.00,Beef Products,OXALIC ACID,mg
524672,6286,"Beef, composite cuts, stewing beef, 0mm (0"") ...",13,245,0.00,Beef Products,OXALIC ACID,mg

In [41]:
df_merged = df_merged.sort_values(by=["FoodDescription", "NutrientName"])
df_merged

,FoodID,FoodDescription,FoodGroupID,NutrientID,NutrientValue,FoodGroupName,NutrientName,NutrientUnit
31442,5282,"Abiyuch, raw",9,221,0.00,Fruits and fruit juices,ALCOHOL,g
437410,5282,"Abiyuch, raw",9,834,0.00,Fruits and fruit juices,ALPHA CAROTENE,µg
20213,5282,"Abiyuch, raw",9,207,0.90,Fruits and fruit juices,"ASH, TOTAL",g
128458,5282,"Abiyuch, raw",9,321,60.00,Fruits and fruit juices,BETA CAROTENE,µg
42484,5282,"Abiyuch, raw",9,262,0.00,Fruits and fruit juices,CAFFEINE,mg
...,...,...,...,...,...,...,...,...
146172,6175,"sweets, syrups, maple, prepackaged",19,401,0.00,Sweets,VITAMIN C,mg
141075,6175,"sweets, syrups, maple, prepackaged",19,339,0.00,Sweets,VITAMIN D (D2 + D3),µg
136076,6175,"sweets, syrups, maple, prepackaged",19,324,0.00,Sweets,VITAMIN D (INTERNATIONAL UNITS),IU
193686,6175,"sweets, syrups, maple, prepackaged",19,430,0.00,Sweets,VITAMIN K,µg
100824,6175,"sweets, syrups, maple, prepackaged",19,309,1.99,Sweets,ZINC,mg

In [42]:
df_merged[df_merged["FoodDescription"] == "Chinese dish, chow mein, chicken"]

,FoodID,FoodDescription,FoodGroupID,NutrientID,NutrientValue,FoodGroupName,NutrientName,NutrientUnit
248232,5,"Chinese dish, chow mein, chicken",22,513,0.356,Mixed Dishes,ALANINE,g
28451,5,"Chinese dish, chow mein, chicken",22,221,0.000,Mixed Dishes,ALCOHOL,g
435431,5,"Chinese dish, chow mein, chicken",22,834,99.000,Mixed Dishes,ALPHA CAROTENE,µg
130689,5,"Chinese dish, chow mein, chicken",22,323,0.430,Mixed Dishes,ALPHA-TOCOPHEROL,mg
240427,5,"Chinese dish, chow mein, chicken",22,511,0.424,Mixed Dishes,ARGININE,g
...,...,...,...,...,...,...,...,...
144822,5,"Chinese dish, chow mein, chicken",22,401,2.000,Mixed Dishes,VITAMIN C,mg
139822,5,"Chinese dish, chow mein, chicken",22,339,0.000,Mixed Dishes,VITAMIN D (D2 + D3),µg
134824,5,"Chinese dish, chow mein, chicken",22,324,1.000,Mixed Dishes,VITAMIN D (INTERNATIONAL UNITS),IU
192744,5,"Chinese dish, chow mein, chicken",22,430,22.000,Mixed Dishes,VITAMIN K,µg
99498,5,"Chinese dish, chow mein, chicken",22,309,0.320,Mixed Dishes,ZINC,mg

In [43]:
nutrition_labels = ['ALCOHOL', 'CAFFEINE', 'CALCIUM', 'CARBOHYDRATE, TOTAL (BY DIFFERENCE)',
                    'CHOLESTEROL', 'COPPER', 'FAT (TOTAL LIPIDS)',
                    'FATTY ACIDS, POLYUNSATURATED, TOTAL',
                    'FATTY ACIDS, SATURATED, TOTAL', 'FIBRE, TOTAL DIETARY', 'IRON', 'LACTOSE']

In [44]:
df_filtered = df_merged["NutrientName"].isin(nutrition_labels)
df_filtered = df_merged[df_filtered]
df_filtered

,FoodID,FoodDescription,FoodGroupID,NutrientID,NutrientValue,FoodGroupName,NutrientName,NutrientUnit
31442,5282,"Abiyuch, raw",9,221,0.000,Fruits and fruit juices,ALCOHOL,g
42484,5282,"Abiyuch, raw",9,262,0.000,Fruits and fruit juices,CAFFEINE,mg
69143,5282,"Abiyuch, raw",9,301,8.000,Fruits and fruit juices,CALCIUM,mg
14523,5282,"Abiyuch, raw",9,205,17.600,Fruits and fruit juices,"CARBOHYDRATE, TOTAL (BY DIFFERENCE)",g
274429,5282,"Abiyuch, raw",9,601,0.000,Fruits and fruit juices,CHOLESTEROL,mg
...,...,...,...,...,...,...,...,...
367177,6175,"sweets, syrups, maple, prepackaged",19,646,0.100,Sweets,"FATTY ACIDS, POLYUNSATURATED, TOTAL",g
280317,6175,"sweets, syrups, maple, prepackaged",19,606,0.036,Sweets,"FATTY ACIDS, SATURATED, TOTAL",g
61921,6175,"sweets, syrups, maple, prepackaged",19,291,0.000,Sweets,"FIBRE, TOTAL DIETARY",g
73043,6175,"sweets, syrups, maple, prepackaged",19,303,1.200,Sweets,IRON,mg
453854,6175,"sweets, syrups, maple, prepackaged",19,213,0.000,Sweets,LACTOSE,g

In [45]:
df_filtered["NutrientUnit"].unique()

array(['g', 'mg'], dtype=object)

In [46]:
unit_conversion_mapper = {"mg": 0.001,
                          "kCal": 0.129598,
                          "µg": 0.000001}

def unit_converter(original_unit):
    return unit_conversion_mapper[original_unit]
    
def unit_conversion(df):
    df = df.dropna(subset=["NutrientValue"])
    df["NutrientValue"] = df.apply(lambda row: (row["NutrientValue"] * unit_converter(row["NutrientUnit"])) if row["NutrientUnit"] != "g" else row["NutrientValue"], axis=1)
    df["NutrientUnit"] = "g"
    return df

df_unit = unit_conversion(df_filtered)
df_unit

,FoodID,FoodDescription,FoodGroupID,NutrientID,NutrientValue,FoodGroupName,NutrientName,NutrientUnit
31442,5282,"Abiyuch, raw",9,221,0.0000,Fruits and fruit juices,ALCOHOL,g
42484,5282,"Abiyuch, raw",9,262,0.0000,Fruits and fruit juices,CAFFEINE,g
69143,5282,"Abiyuch, raw",9,301,0.0080,Fruits and fruit juices,CALCIUM,g
14523,5282,"Abiyuch, raw",9,205,17.6000,Fruits and fruit juices,"CARBOHYDRATE, TOTAL (BY DIFFERENCE)",g
274429,5282,"Abiyuch, raw",9,601,0.0000,Fruits and fruit juices,CHOLESTEROL,g
...,...,...,...,...,...,...,...,...
367177,6175,"sweets, syrups, maple, prepackaged",19,646,0.1000,Sweets,"FATTY ACIDS, POLYUNSATURATED, TOTAL",g
280317,6175,"sweets, syrups, maple, prepackaged",19,606,0.0360,Sweets,"FATTY ACIDS, SATURATED, TOTAL",g
61921,6175,"sweets, syrups, maple, prepackaged",19,291,0.0000,Sweets,"FIBRE, TOTAL DIETARY",g
73043,6175,"sweets, syrups, maple, prepackaged",19,303,0.0012,Sweets,IRON,g
453854,6175,"sweets, syrups, maple, prepackaged",19,213,0.0000,Sweets,LACTOSE,g

In [47]:
emlimate_categories = ["Babyfoods", "Fast Foods", "Mixed Dishes", "Snacks"]
df_unit1 = df_unit[~df_unit["FoodGroupName"].isin(emlimate_categories)]
df_unit1["CO2 Emission per Kg"] = df_unit1.apply(lambda row: category_mapper(row["FoodGroupName"], footprints, map_category), axis=1)
df_unit1

/var/folders/c5/pphx1c0n3lb12sy85_ybqxqm0000gn/T/ipykernel_1645/3468222344.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unit1["CO2 Emission per Kg"] = df_unit1.apply(lambda row: category_mapper(row["FoodGroupName"], footprints, map_category), axis=1)

,FoodID,FoodDescription,FoodGroupID,NutrientID,NutrientValue,FoodGroupName,NutrientName,NutrientUnit,CO2 Emission per Kg
31442,5282,"Abiyuch, raw",9,221,0.0000,Fruits and fruit juices,ALCOHOL,g,0.68250
42484,5282,"Abiyuch, raw",9,262,0.0000,Fruits and fruit juices,CAFFEINE,g,0.68250
69143,5282,"Abiyuch, raw",9,301,0.0080,Fruits and fruit juices,CALCIUM,g,0.68250
14523,5282,"Abiyuch, raw",9,205,17.6000,Fruits and fruit juices,"CARBOHYDRATE, TOTAL (BY DIFFERENCE)",g,0.68250
274429,5282,"Abiyuch, raw",9,601,0.0000,Fruits and fruit juices,CHOLESTEROL,g,0.68250
...,...,...,...,...,...,...,...,...,...
367177,6175,"sweets, syrups, maple, prepackaged",19,646,0.1000,Sweets,"FATTY ACIDS, POLYUNSATURATED, TOTAL",g,1.58195
280317,6175,"sweets, syrups, maple, prepackaged",19,606,0.0360,Sweets,"FATTY ACIDS, SATURATED, TOTAL",g,1.58195
61921,6175,"sweets, syrups, maple, prepackaged",19,291,0.0000,Sweets,"FIBRE, TOTAL DIETARY",g,1.58195
73043,6175,"sweets, syrups, maple, prepackaged",19,303,0.0012,Sweets,IRON,g,1.58195
453854,6175,"sweets, syrups, maple, prepackaged",19,213,0.0000,Sweets,LACTOSE,g,1.58195

In [20]:
# df_unit1["CO2 Emission per g"] = df_unit1["CO2 Emission per Kg"] * 1000
df_unit1

,FoodID,FoodDescription,FoodGroupID,NutrientID,NutrientValue,FoodGroupName,NutrientName,NutrientUnit,CO2 Emission per Kg
31442,5282,"Abiyuch, raw",9,221,0.0000,Fruits and fruit juices,ALCOHOL,g,0.68250
42484,5282,"Abiyuch, raw",9,262,0.0000,Fruits and fruit juices,CAFFEINE,g,0.68250
69143,5282,"Abiyuch, raw",9,301,0.0080,Fruits and fruit juices,CALCIUM,g,0.68250
14523,5282,"Abiyuch, raw",9,205,17.6000,Fruits and fruit juices,"CARBOHYDRATE, TOTAL (BY DIFFERENCE)",g,0.68250
274429,5282,"Abiyuch, raw",9,601,0.0000,Fruits and fruit juices,CHOLESTEROL,g,0.68250
...,...,...,...,...,...,...,...,...,...
367177,6175,"sweets, syrups, maple, prepackaged",19,646,0.1000,Sweets,"FATTY ACIDS, POLYUNSATURATED, TOTAL",g,1.58195
280317,6175,"sweets, syrups, maple, prepackaged",19,606,0.0360,Sweets,"FATTY ACIDS, SATURATED, TOTAL",g,1.58195
61921,6175,"sweets, syrups, maple, prepackaged",19,291,0.0000,Sweets,"FIBRE, TOTAL DIETARY",g,1.58195
73043,6175,"sweets, syrups, maple, prepackaged",19,303,0.0012,Sweets,IRON,g,1.58195
453854,6175,"sweets, syrups, maple, prepackaged",19,213,0.0000,Sweets,LACTOSE,g,1.58195

In [21]:
df_unit1.to_csv("cleaned_data/ingredients2.csv", index=False)

In [48]:
df_unit1["FoodGroupName"].unique().tolist()

['Fruits and fruit juices',
 'Vegetables and Vegetable Products',
 'Finfish and Shellfish Products',
 'Beverages',
 'Fats and Oils',
 'Baked Products',
 'Spices and Herbs',
 'Legumes and Legume Products',
 'Beef Products',
 'Dairy and Egg Products',
 'Sweets',
 'Breakfast cereals',
 'Poultry Products',
 'Sausages and Luncheon meats',
 'Soups, Sauces and Gravies',
 'Lamb, Veal and Game',
 'Cereals, Grains and Pasta',
 'Nuts and Seeds',
 'Pork Products']

In [49]:
nutrient_df = df_unit1.pivot(index=["FoodID", "FoodGroupName", "FoodDescription"], columns="NutrientName", values="NutrientValue").reset_index()
nutrient_df

NutrientName,FoodID,FoodGroupName,FoodDescription,ALCOHOL,CAFFEINE,CALCIUM,"CARBOHYDRATE, TOTAL (BY DIFFERENCE)",CHOLESTEROL,COPPER,FAT (TOTAL LIPIDS),"FATTY ACIDS, POLYUNSATURATED, TOTAL","FATTY ACIDS, SATURATED, TOTAL","FIBRE, TOTAL DIETARY",IRON,LACTOSE
0,6,Baked Products,Corn fritter,0.0,0.000,0.074,38.62,0.061,0.000101,21.24,5.564,5.455,2.0,0.00250,0.963
1,13,Spices and Herbs,"Vinegar, cider",0.0,0.000,0.007,0.93,0.000,0.000008,0.00,0.000,0.000,0.0,0.00020,0.000
2,14,Spices and Herbs,"Vinegar, distilled (white)",0.0,0.000,0.006,0.04,0.000,0.000006,0.00,0.000,0.000,0.0,0.00003,NaN
3,16,Dairy and Egg Products,"Butter, whipped",0.0,0.000,0.024,0.06,0.219,0.000016,81.11,3.012,50.489,0.0,0.00016,NaN
4,17,Dairy and Egg Products,"Butter oil, anhydrous",0.0,0.000,0.004,0.00,0.256,0.000001,99.48,3.694,61.924,0.0,0.00000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5201,503365,Fruits and fruit juices,"Orange juice, frozen concentrate, diluted, wit...",NaN,NaN,0.113,9.12,0.000,0.000022,0.07,0.017,0.016,0.3,0.00009,NaN
5202,503366,Fats and Oils,"Margarine, tub, hydrogenated, soybean oil",NaN,NaN,0.011,3.80,0.000,0.000016,77.16,23.170,13.900,0.0,0.00000,NaN
5203,503367,Fats and Oils,"Margarine, tub, hydrogenated, canola oil",NaN,NaN,0.010,3.73,0.000,0.000010,77.63,26.383,14.552,0.0,0.00000,NaN
5204,503379,Beverages,"Chocolate syrup, thin type, less sugar, with a...",0.0,NaN,0.570,67.57,0.000,NaN,0.00,0.000,0.000,0.0,0.00950,NaN
5205,503380,Baked Products,"Granola bar, chewy, high fibre, oats and choco...",0.0,0.003,0.000,69.78,0.000,NaN,10.00,2.334,3.397,14.3,0.00090,0.000

In [50]:
nutrient_df = nutrient_df.replace(np.nan, 0)
nutrient_df

NutrientName,FoodID,FoodGroupName,FoodDescription,ALCOHOL,CAFFEINE,CALCIUM,"CARBOHYDRATE, TOTAL (BY DIFFERENCE)",CHOLESTEROL,COPPER,FAT (TOTAL LIPIDS),"FATTY ACIDS, POLYUNSATURATED, TOTAL","FATTY ACIDS, SATURATED, TOTAL","FIBRE, TOTAL DIETARY",IRON,LACTOSE
0,6,Baked Products,Corn fritter,0.0,0.000,0.074,38.62,0.061,0.000101,21.24,5.564,5.455,2.0,0.00250,0.963
1,13,Spices and Herbs,"Vinegar, cider",0.0,0.000,0.007,0.93,0.000,0.000008,0.00,0.000,0.000,0.0,0.00020,0.000
2,14,Spices and Herbs,"Vinegar, distilled (white)",0.0,0.000,0.006,0.04,0.000,0.000006,0.00,0.000,0.000,0.0,0.00003,0.000
3,16,Dairy and Egg Products,"Butter, whipped",0.0,0.000,0.024,0.06,0.219,0.000016,81.11,3.012,50.489,0.0,0.00016,0.000
4,17,Dairy and Egg Products,"Butter oil, anhydrous",0.0,0.000,0.004,0.00,0.256,0.000001,99.48,3.694,61.924,0.0,0.00000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5201,503365,Fruits and fruit juices,"Orange juice, frozen concentrate, diluted, wit...",0.0,0.000,0.113,9.12,0.000,0.000022,0.07,0.017,0.016,0.3,0.00009,0.000
5202,503366,Fats and Oils,"Margarine, tub, hydrogenated, soybean oil",0.0,0.000,0.011,3.80,0.000,0.000016,77.16,23.170,13.900,0.0,0.00000,0.000
5203,503367,Fats and Oils,"Margarine, tub, hydrogenated, canola oil",0.0,0.000,0.010,3.73,0.000,0.000010,77.63,26.383,14.552,0.0,0.00000,0.000
5204,503379,Beverages,"Chocolate syrup, thin type, less sugar, with a...",0.0,0.000,0.570,67.57,0.000,0.000000,0.00,0.000,0.000,0.0,0.00950,0.000
5205,503380,Baked Products,"Granola bar, chewy, high fibre, oats and choco...",0.0,0.003,0.000,69.78,0.000,0.000000,10.00,2.334,3.397,14.3,0.00090,0.000

In [52]:
def find_closest_alternative(food, out_of_category_attempt, within_category_attempt):
    food_emission_value = df_unit1[df_unit1["FoodDescription"] == food]["CO2 Emission per Kg"].values[0]
    footprints_list = footprints[footprints["GHG emissions per kilogram"] == food_emission_value]
    filtered_footprints_list = footprints[footprints["GHG emissions per kilogram"] < food_emission_value]["Entity"].tolist()
    all_value_list = map_category.values()
    filtered_list = [category for category in filtered_footprints_list if category in all_value_list]
    
    food = nutrient_df[nutrient_df["FoodDescription"] == food]
    alcohol = food["ALCOHOL"].values[0]
    caffeine = food["CAFFEINE"].values[0]
    calcium = food["CALCIUM"].values[0]
    carbohydrate = food["CARBOHYDRATE, TOTAL (BY DIFFERENCE)"].values[0]
    cholesterol = food["CHOLESTEROL"].values[0]
    lipid = food["FAT (TOTAL LIPIDS)"].values[0]
    poly_acid = food["FATTY ACIDS, POLYUNSATURATED, TOTAL"].values[0]
    saturated_acid = food["FATTY ACIDS, SATURATED, TOTAL"].values[0]
    iron = food["IRON"].values[0]
    lactose = food["LACTOSE"].values[0]
    
    nutrient_df["Error Value"] = 0
    
    try_count = out_of_category_attempt
    
    def compute_ols(alcohol, caffeine, calcium, carbohydrate, cholesterol, lipid, poly_acid, saturated_acid, iron, lactose, nutrient_df, try_count):
        category = filtered_list[try_count]
        mapped_category = list((i for i in map_category if map_category[i] == category))
        nutrient_df = nutrient_df[nutrient_df["FoodGroupName"] == mapped_category[0]]
        
        for ind, row in nutrient_df.iterrows():
            alcohol_error = (row["ALCOHOL"] - alcohol) ** 2
            caffeine_error = (row["CAFFEINE"] - caffeine) ** 2
            calcium_error = (row["CALCIUM"] - calcium) ** 2
            carbohydate_error = (row["CARBOHYDRATE, TOTAL (BY DIFFERENCE)"] - carbohydrate) ** 2
            cholesterol_error = (row["CHOLESTEROL"] - cholesterol) ** 2
            lipid_error = (row["FAT (TOTAL LIPIDS)"] - lipid) ** 2
            poly_acid_error = (row["FATTY ACIDS, POLYUNSATURATED, TOTAL"] - poly_acid) ** 2
            saturated_acid_error = (row["FATTY ACIDS, SATURATED, TOTAL"] - saturated_acid) ** 2
            iron_error = (row["IRON"] - iron) ** 2
            lactose_error = (row["LACTOSE"] - lactose) ** 2
            
            all_error = alcohol_error + caffeine_error + calcium_error + carbohydate_error + cholesterol_error + lipid_error + poly_acid_error + saturated_acid_error + iron_error + lactose_error
            nutrient_df.loc[ind, "Error Value"] = all_error
        
        min_error_df = nutrient_df.sort_values(by=["Error Value"], ascending=True)
        
        try:
            return min_error_df.iloc[within_category_attempt]["FoodDescription"]
        except:
            try_count += 1
            return compute_ols(alcohol, caffeine, calcium, carbohydrate, cholesterol, lipid, poly_acid, saturated_acid, iron, lactose, nutrient_df, try_count)
    
    error_df = compute_ols(alcohol, caffeine, calcium, carbohydrate, cholesterol, lipid, poly_acid, saturated_acid, iron, lactose, nutrient_df, try_count)
        
    return error_df

find_closest_alternative("Pork, carcass, lean and fat, raw", 0, 0)

/var/folders/c5/pphx1c0n3lb12sy85_ybqxqm0000gn/T/ipykernel_1645/3697828830.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nutrient_df.loc[ind, "Error Value"] = all_error

'Nuts, coconut milk (liquid from grated meat and water), raw'

In [23]:
((((31368 * 1000000000) + (12577 * 1000000000)) / (15.3 * 1000000)) / 365 / 3) / 1000

2.6230339928970063

In [ ]:
nutrient_df.to_csv("cleaned_data/nutrient_df.csv", index=False)